perso_ugliest_homepage:
    path:     /index
    defaults: { _controller: "PersoUgliestBundle:Default:index" }

perso_ugliest_compare:
    path:     /compare/{id}
    defaults: { _controller: "PersoUgliestBundle:Default:compare", id = null }
    
perso_ugliest_list:
    path:     /list
    defaults: { _controller: "PersoUgliestBundle:Default:list" }  
 
perso_ugliest_create:
    path:     /create
    defaults: { _controller: "PersoUgliestBundle:Default:create" }

perso_ugliest_ranking:
    path:     /ranking
    defaults: { _controller: "PersoUgliestBundle:Default:ranking" }    