parameters:
#    perso_ugliest.example.class: Perso\UgliestBundle\Example

services:
#    perso_ugliest.example:
#        class: %perso_ugliest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
